name: BradTate
favicon: null
layout_spectrum: 0.4172403116244823
typography_spectrum: 0.9905639537610114
title: My Grid Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.818003784166649
  lightness: 0.6892659065779299
  saturation: 0.48838085518218577
  rhythmicContrast: 0.5512677871156484
purpose: []
